// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace api.Data.Migrations {
    [DbContext (typeof (StoreContext))]
    partial class StoreContextModelSnapshot : ModelSnapshot {
        protected override void BuildModel (ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation ("ProductVersion", "3.1.1");

            modelBuilder.Entity ("api.Entities.Product", b => {
                b.Property<Guid> ("Id")
                    .ValueGeneratedOnAdd ()
                    .HasColumnType ("TEXT");

                b.Property<string> ("Name")
                    .HasColumnType ("TEXT");

                b.HasKey ("Id");

                b.ToTable ("Products");
            });
#pragma warning restore 612, 618
        }
    }
}